info:
  contact: { }
paths:
  /index:
    get:
      consumes:
        - application/json
      description: 应用正常访问
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 首页
      tags:
        - 首页
  /user/create:
    post:
      consumes:
        - application/json
      description: 新增用户
      parameters:
        - description: 请求体
          in: body
          name: data
          required: true
          schema:
            example: "{\n \"username\": \"张三\", \n \"password\": \"123\"\n}"
            type: string
      produces:
        - application/json
      responses:
        "200":
          description: code", "msg", "data"}
          schema:
            type: string
      summary: 新增用户
      tags:
        - 用户
  /user/delete:
    get:
      consumes:
        - application/json
      description: 删除用户
      parameters:
        - description: id
          in: query
          name: id
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: code", "msg"}
          schema:
            type: string
      summary: 删除用户
      tags:
        - 用户
  /user/list:
    get:
      consumes:
        - application/json
      description: 查询用户列表
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户列表
      tags:
        - 用户
  /user/update:
    post:
      consumes:
        - application/json
      description: 修改用户
      parameters:
        - description: 请求体
          in: body
          name: data
          required: true
          schema:
            example: "{\n \"id\": \"1\", \n \"username\": \"张三\", \n \"password\": \"123\"\n}"
            type: string
      produces:
        - application/json
      responses:
        "200":
          description: code", "msg", "data"}
          schema:
            type: string
      summary: 修改用户
      tags:
        - 用户
swagger: "2.0"
